### ISSUE TITLE
Not on NPM anymore

### ISSUE THREAD

**Issue by mattydoincode** [jorgetolentinog/mocha-babel#5]
Is there a reason why this library is off npm?

**Comment by andpor** [comment]
same issue ...we run a build this morning and npm install failed with error mocha-babel not in registry...

**Comment by andreaferretti** [comment]
Same problem here... I think it was removed because it is not needed on Babel6, but migrating from Babel5 to Babel6 is everything but trivial (if possible at all)

**Comment by andreaferretti** [comment]
@mattydoincode @andpor It is enough to run `mocha --compilers js:babel/register` instead of `mocha --compilers js:mocha-babel`

**Comment by jorgetolentinog** [comment]
asdasd

**Comment by jorgetolentinog** [comment]
asdada
